export const THEMES = {
  classic: {
    name: "Classic",
    properties: {
      0:  { displayName: "Go",                 color: "#FFFFFF" },
      1:  { displayName: "Mediterranean Avenue", color: "#8B4513" },
      2:  { displayName: "Community Chest",       color: "#ffe933" },
      3:  { displayName: "Baltic Avenue",       color: "#8B4513" },
      4:  { displayName: "Income Tax",          color: "#FF0000" },
      5:  { displayName: "Reading Railroad",    color: "#000000" },
      6:  { displayName: "Oriental Avenue",     color: "#87CEFA" },
      7:  { displayName: "Chance",              color: "#ffb933" },
      8:  { displayName: "Vermont Avenue",      color: "#87CEFA" },
      9:  { displayName: "Connecticut Avenue",  color: "#87CEFA" },
      10: { displayName: "Jail / Just Visiting",color: "#FFFFFF" },
      11: { displayName: "St. Charles Place",   color: "#FF69B4" },
      12: { displayName: "Electric Company",    color: "#FFFFFF" },
      13: { displayName: "States Avenue",       color: "#FF69B4" },
      14: { displayName: "Virginia Avenue",     color: "#FF69B4" },
      15: { displayName: "Pennsylvania Railroad", color: "#000000" },
      16: { displayName: "St. James Place",     color: "#FFA500" },
      17: { displayName: "Community Chest",     color: "#ffe933" },
      18: { displayName: "Tennessee Avenue",    color: "#FFA500" },
      19: { displayName: "New York Avenue",     color: "#FFA500" },
      20: { displayName: "Free Parking",        color: "#FFFFFF" },
      21: { displayName: "Kentucky Avenue",     color: "#FF0000" },
      22: { displayName: "Chance",              color: "#FFFFFF" },
      23: { displayName: "Indiana Avenue",      color: "#FF0000" },
      24: { displayName: "Illinois Avenue",     color: "#FF0000" },
      25: { displayName: "B. & O. Railroad",    color: "#000000" },
      26: { displayName: "Atlantic Avenue",     color: "#FFFF00" },
      27: { displayName: "Ventnor Avenue",      color: "#FFFF00" },
      28: { displayName: "Water Works",         color: "#FFFFFF" },
      29: { displayName: "Marvin Gardens",      color: "#FFFF00" },
      30: { displayName: "Go To Jail",          color: "#FF0000" },
      31: { displayName: "Pacific Avenue",      color: "#008000" },
      32: { displayName: "North Carolina Avenue", color: "#008000" },
      33: { displayName: "Community Chest",     color: "#ffe933" },
      34: { displayName: "Pennsylvania Avenue", color: "#008000" },
      35: { displayName: "Short Line Railroad", color: "#000000" },
      36: { displayName: "Chance",              color: "#ffb933" },
      37: { displayName: "Park Place",          color: "#00008B" },
      38: { displayName: "Luxury Tax",          color: "#FF0000" },
      39: { displayName: "Boardwalk",           color: "#00008B" },
    },
  },

  dark: {
    name: "Dark",
    properties: {
      0:  { displayName: "Go",                 color: "#212121" },
      1:  { displayName: "Mediterranean Ave",  color: "#4E342E" },
      2:  { displayName: "Community Chest",    color: "#616161" },
      3:  { displayName: "Baltic Ave",         color: "#4E342E" },
      4:  { displayName: "Income Tax",         color: "#B71C1C" },
      5:  { displayName: "Reading Railroad",   color: "#212121" },
      6:  { displayName: "Oriental Ave",       color: "#1565C0" },
      7:  { displayName: "Chance",             color: "#616161" },
      8:  { displayName: "Vermont Ave",        color: "#1565C0" },
      9:  { displayName: "Connecticut Ave",    color: "#1565C0" },
      10: { displayName: "Jail / Just Visiting",color: "#424242" },
      11: { displayName: "St. Charles Pl",     color: "#AD1457" },
      12: { displayName: "Electric Co",        color: "#BDBDBD" },
      13: { displayName: "States Ave",         color: "#AD1457" },
      14: { displayName: "Virginia Ave",       color: "#AD1457" },
      15: { displayName: "Pennsylvania R.R.",  color: "#212121" },
      16: { displayName: "St. James Pl",       color: "#EF6C00" },
      17: { displayName: "Community Chest",    color: "#616161" },
      18: { displayName: "Tennessee Ave",      color: "#EF6C00" },
      19: { displayName: "New York Ave",       color: "#EF6C00" },
      20: { displayName: "Free Parking",       color: "#424242" },
      21: { displayName: "Kentucky Ave",       color: "#C62828" },
      22: { displayName: "Chance",             color: "#616161" },
      23: { displayName: "Indiana Ave",        color: "#C62828" },
      24: { displayName: "Illinois Ave",       color: "#C62828" },
      25: { displayName: "B. & O. R.R.",       color: "#212121" },
      26: { displayName: "Atlantic Ave",       color: "#FDD835" },
      27: { displayName: "Ventnor Ave",        color: "#FDD835" },
      28: { displayName: "Water Works",        color: "#BDBDBD" },
      29: { displayName: "Marvin Gardens",     color: "#FDD835" },
      30: { displayName: "Go To Jail",         color: "#B71C1C" },
      31: { displayName: "Pacific Ave",        color: "#2E7D32" },
      32: { displayName: "N. Carolina Ave",    color: "#2E7D32" },
      33: { displayName: "Community Chest",    color: "#616161" },
      34: { displayName: "Pennsylvania Ave",   color: "#2E7D32" },
      35: { displayName: "Short Line R.R.",    color: "#212121" },
      36: { displayName: "Chance",             color: "#616161" },
      37: { displayName: "Park Place",         color: "#0D47A1" },
      38: { displayName: "Luxury Tax",         color: "#B71C1C" },
      39: { displayName: "Boardwalk",          color: "#0D47A1" },
    },
  },

  haunted: {
    name: "Spooky",
    properties: {
      0:  { displayName: "Haunted Gate",       color: "#220022" },
      1:  { displayName: "Cursed Mire",        color: "#3A1A1A" },
      2:  { displayName: "Community Chest",    color: "#330033" },
      3:  { displayName: "Bleeding Hollow",    color: "#4B2E2E" },
      4:  { displayName: "Spirit Toll",        color: "#6A1A1A" },
      5:  { displayName: "Ghost Train",        color: "#1C1C1C" },
      6:  { displayName: "Witch’s Path",       color: "#3E2A3E" },
      7:  { displayName: "Spectral Chance",    color: "#330033" },
      8:  { displayName: "Phantom Road",       color: "#452545" },
      9:  { displayName: "Haunted Hollow",     color: "#552F2F" },
      10: { displayName: "The Dungeon",        color: "#220022" },
      11: { displayName: "Forsaken Grove",     color: "#2F2F3F" },
      12: { displayName: "Electrified Tomb",   color: "#222222" },
      13: { displayName: "Blackened Glade",    color: "#4A3A4A" },
      14: { displayName: "Graveyard Lane",     color: "#3B1F1F" },
      15: { displayName: "Phantom Rails",      color: "#1C1C1C" },
      16: { displayName: "Coven Circle",       color: "#5D2F5D" },
      17: { displayName: "Community Chest",    color: "#330033" },
      18: { displayName: "Wailing Pines",      color: "#4E3B4E" },
      19: { displayName: "Bloodmoon Pass",     color: "#5A1A1A" },
      20: { displayName: "Eerie Clearing",     color: "#220022" },
      21: { displayName: "Sanguine Road",      color: "#6A1A1A" },
      22: { displayName: "Spectral Chance",    color: "#330033" },
      23: { displayName: "Cryptic Alley",      color: "#3F2A3F" },
      24: { displayName: "Shadowed Veil",      color: "#2B1B2B" },
      25: { displayName: "Phantom Express",    color: "#1C1C1C" },
      26: { displayName: "Tombstone Terrace",  color: "#3C2C3C" },
      27: { displayName: "Specter’s Pass",     color: "#4C2B4C" },
      28: { displayName: "Dark Waters",        color: "#111111" },
      29: { displayName: "Midnight Hollow",    color: "#2D1B2D" },
      30: { displayName: "Curse of the Cellar",color: "#6A1A1A" },
      31: { displayName: "Grim Forest",        color: "#2E2B28" },
      32: { displayName: "Deadman’s Crossing", color: "#1F1B1F" },
      33: { displayName: "Community Chest",    color: "#330033" },
      34: { displayName: "Blackwood Trail",    color: "#3A2E2B" },
      35: { displayName: "Rust Line",          color: "#1C1C1C" },
      36: { displayName: "Spectral Chance",    color: "#330033" },
      37: { displayName: "Spectral Court",     color: "#3B243B" },
      38: { displayName: "Forbidden Offering", color: "#6A1A1A" },
      39: { displayName: "Wraith’s End",       color: "#220022" },
    },
  },
};
