name: Build and deploy Python + React app to Azure Web App - reactopoly-online

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Setup Node.js for frontend build
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'   # or your preferred Node version

      # Build React frontend
      - name: Build React frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build   # generates 'dist' or 'build' folder (depending on config)

      # Setup Python for backend
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install backend dependencies
      - name: Install Python dependencies
        working-directory: ./backend
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r backend/requirements.txt

      # Copy frontend build output into backend static folder (adjust if needed)
      - name: Copy React build into backend static folder
        run: |
          # Example: copying 'dist' folder from frontend to backend/public or backend/static
          mkdir -p ./backend/public
          cp -r ./frontend/dist/* ./backend/public/

      # Zip everything in backend folder for deployment
      - name: Zip artifact for deployment
        run: |
          cd backend
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-react-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-react-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'reactopoly-online'
          slot-name: 'Production'
